In [1]:
import pandas as pd
import numpy as np

In [ ]:
response_embeddings = np.load(r"C:\Users\BHUPATHI NADAR\OneDrive\Desktop\Main_project\MLSC-Task\Data\response_embeddings.npy")
document_embeddings = np.load(r"C:\Users\BHUPATHI NADAR\OneDrive\Desktop\Main_project\MLSC-Task\Data\document_embeddings.npy")
question_embeddings=np.load(r"C:\Users\BHUPATHI NADAR\OneDrive\Desktop\Main_project\MLSC-Task\Data\question_embeddings.npy")

In [5]:
df = pd.read_csv(
    r"C:\Users\BHUPATHI NADAR\OneDrive\Desktop\Main_project\MLSC-Task\Data\updated_data.csv",
    engine="python",
    on_bad_lines="skip"
)
print(len(df))

95586

In [7]:
df["response_embeddings"] = list(response_embeddings)
df["document_embeddings"] = list(document_embeddings)
df["question_embeddings"] = list(question_embeddings)

In [8]:
df.head()

,question,documents,response,sentence_support_information,label,response_embeddings,document_embeddings,question_embeddings
0,What role does T-cell count play in severe hum...,['Title: Emergent severe acute respiratory dis...,The T-cell count plays a crucial role in sever...,[{'explanation': 'This sentence is supported b...,GROUNDED,"[0.009646302, 0.033377603, 0.016678933, -2.471...","[-0.028878609, 0.028723784, 0.00075698394, -0....","[-0.032216262, 0.024737483, -0.017189968, -0.0..."
1,What is MVO?,['Title: Gene Knockdowns in Adult Animals: PPM...,MVO is not defined or mentioned in the provide...,[{'explanation': 'The sentence correctly state...,GROUNDED,"[-0.0362419, -0.0003036126, -0.029364685, 0.00...","[-0.054388516, -0.0072670355, -0.008731055, -0...","[-0.022642525, -0.0048539774, -0.061880574, 0...."
2,What have sero-surveys of MERS virus found?,"['Title: MERS coronavirus: diagnostics, epidem...",Sero-surveys of MERS virus found no sign of ME...,[{'explanation': 'This sentence is partly supp...,PARTIALLY_GROUNDED,"[0.087099895, 0.08424325, -0.02455617, -0.0213...","[-0.0006244028, 0.11510501, -0.06748915, 0.005...","[-0.024132326, 0.055474468, -0.035059784, 0.01..."
3,How were untreated MDA-MB-231 cells labeled?,['Title: Kinome-Wide siRNA Screening Identifie...,The untreated MDA-MB-231 cells were labeled wi...,[{'explanation': 'The sentence is fully suppor...,GROUNDED,"[-0.044364452, -0.050517034, -0.10471764, -0.0...","[-0.032106902, -0.08865902, -0.13841778, -0.09...","[-0.020781826, 0.044006065, -0.13403462, -0.10..."
4,What is the number of inhabitants of Reunion I...,['Title: Pandemic Influenza Due to pH1N1/2009 ...,"Reunion Island has a population of 850,000 inh...",[{'explanation': 'This sentence claims that Re...,GROUNDED,"[0.03647383, -0.074744254, 0.023043087, 0.0136...","[0.021294175, -0.011302552, 0.02271998, 0.0287...","[0.03453502, -0.0344854, 0.002928231, 0.011495..."

In [9]:
df.columns

Index(['question', 'documents', 'response', 'sentence_support_information',
       'label', 'response_embeddings', 'document_embeddings',
       'question_embeddings'],
      dtype='str')

In [10]:
df=df.drop(['question', 'documents', 'response', 'sentence_support_information'],axis=1)

In [11]:
df.head()

,label,response_embeddings,document_embeddings,question_embeddings
0,GROUNDED,"[0.009646302, 0.033377603, 0.016678933, -2.471...","[-0.028878609, 0.028723784, 0.00075698394, -0....","[-0.032216262, 0.024737483, -0.017189968, -0.0..."
1,GROUNDED,"[-0.0362419, -0.0003036126, -0.029364685, 0.00...","[-0.054388516, -0.0072670355, -0.008731055, -0...","[-0.022642525, -0.0048539774, -0.061880574, 0...."
2,PARTIALLY_GROUNDED,"[0.087099895, 0.08424325, -0.02455617, -0.0213...","[-0.0006244028, 0.11510501, -0.06748915, 0.005...","[-0.024132326, 0.055474468, -0.035059784, 0.01..."
3,GROUNDED,"[-0.044364452, -0.050517034, -0.10471764, -0.0...","[-0.032106902, -0.08865902, -0.13841778, -0.09...","[-0.020781826, 0.044006065, -0.13403462, -0.10..."
4,GROUNDED,"[0.03647383, -0.074744254, 0.023043087, 0.0136...","[0.021294175, -0.011302552, 0.02271998, 0.0287...","[0.03453502, -0.0344854, 0.002928231, 0.011495..."

In [12]:
df.shape

(95586, 4)

In [14]:
import numpy as np

def row_wise_cosine_similarity(A, B):
    A_norm = A / np.linalg.norm(A, axis=1, keepdims=True)
    B_norm = B / np.linalg.norm(B, axis=1, keepdims=True)
    return np.sum(A_norm * B_norm, axis=1)

doc_response_similarity = row_wise_cosine_similarity(document_embeddings, response_embeddings)
question_response_similarity = row_wise_cosine_similarity(question_embeddings, response_embeddings)
question_document_similarity = row_wise_cosine_similarity(question_embeddings, document_embeddings)

In [15]:
df["doc_response_similarity"] = doc_response_similarity
df["question_response_similarity"] = question_response_similarity
df["question_document_similarity"] = question_document_similarity

In [16]:
df.head()

,label,response_embeddings,document_embeddings,question_embeddings,doc_response_similarity,question_response_similarity,question_document_similarity
0,GROUNDED,"[0.009646302, 0.033377603, 0.016678933, -2.471...","[-0.028878609, 0.028723784, 0.00075698394, -0....","[-0.032216262, 0.024737483, -0.017189968, -0.0...",0.782924,0.901967,0.729742
1,GROUNDED,"[-0.0362419, -0.0003036126, -0.029364685, 0.00...","[-0.054388516, -0.0072670355, -0.008731055, -0...","[-0.022642525, -0.0048539774, -0.061880574, 0....",0.211373,0.701803,0.096944
2,PARTIALLY_GROUNDED,"[0.087099895, 0.08424325, -0.02455617, -0.0213...","[-0.0006244028, 0.11510501, -0.06748915, 0.005...","[-0.024132326, 0.055474468, -0.035059784, 0.01...",0.825851,0.716620,0.649443
3,GROUNDED,"[-0.044364452, -0.050517034, -0.10471764, -0.0...","[-0.032106902, -0.08865902, -0.13841778, -0.09...","[-0.020781826, 0.044006065, -0.13403462, -0.10...",0.583459,0.641137,0.506321
4,GROUNDED,"[0.03647383, -0.074744254, 0.023043087, 0.0136...","[0.021294175, -0.011302552, 0.02271998, 0.0287...","[0.03453502, -0.0344854, 0.002928231, 0.011495...",0.306352,0.847259,0.340603

In [17]:
df.to_csv(r"C:\Users\BHUPATHI NADAR\OneDrive\Desktop\Main_project\MLSC-Task\Data\updated_semantic_data.csv", index=False)